### ISSUE TITLE
MD: UI UX Design

### ISSUE THREAD

**Issue by agung-adhinata** [Bangkit-WSLTA-Capstone/mobile-edusign#1]
## Why we need this?
as for pre-requirement for building Capstone App, we need to create UI UX design for it's mobile app so we know what kind of component should we created, while we waiting the ML team to create the model.

### NOTE:
Link of UI UX design will we put at `README.MD` of this repository or at dashboard of this Github Project

**Comment by dxxta** [comment]
noted

**Comment by agung-adhinata** [comment]
Cari ini @dxxta , sekiranya Screenshot buat inspirasi desain aplikasi kita biar bisa kita selesaiin segera

kemudian untuk link _Figma_ nya sudah saya semat di Project Overview (bagian sidebar)

Buat jaga - jaga, saya juga taruh disini [linknya](https://www.figma.com/design/pbZrHK9YpKmKbUNS3VjCUx/Wireframe?node-id=0%3A1&t=29GnwKsjq1zKgoWK-1)
