### ISSUE TITLE
bug: Can't logout, navigation always redirecting back to backState (app_home)

### ISSUE THREAD

**Issue by dxxta** [Bangkit-WSLTA-Capstone/mobile-edusign#9]
The issue happens when i was trying to implementing the **Logout** feature in **MenuScreen**. Find out when its successfully redirecting to **LoginScreen**, the `loginStatus` always return `Status_Success`. Unexpectedly when i restart the app after i hit logout button, it just redirecting finely to login page

<img width="833" alt="image" src="https://github.com/Bangkit-WSLTA-Capstone/mobile-edusign/assets/72371776/85241322-bc72-49bd-b56a-594d689ff162">

> Notes the codes above were running fine, the tokens were successfully removed

- [x] Fix redirecting issue submitted by event listener
- [x] Test logout feature

**Comment by dxxta** [comment]
Please take a look @agung-adhinata

**Comment by agung-adhinata** [comment]
resolved, I forgot to clear the state of the viewModel after login.

it have been fixed in 5c2df7e5bb6580558b873fbcf3fe95767cd984ae commit, take a look @dxxta
